version: '2'
services:
    mariadb:
        image: 'bitnami/mariadb:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - /path/to/mariadb-persistence:/bitnami/mariadb

