FROM tinylab/cloud-ubuntu-cn
MAINTAINER Wu Zhangjin <wuzhangjin@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /home/ubuntu/

RUN apt-get -y update

# Chinese input support
RUN apt-get install -y --force-yes \
	ibus ibus-sunpinyin dbus-x11\
	terminator \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/cache/apt/archives/*.deb

RUN rm -rf /var/lib/apt/lists/*

ADD system/cn_input/ /

EXPOSE 5900 22

WORKDIR /

ENTRYPOINT ["/startup.sh"]
